all:
	javac -encoding "UTF-8" -d ./TerminalBin/ -classpath "./*" src/*.java

updateMasterList:
	java -classpath "./TerminalBin/:./*" Main updateMasterList

crawlDoc:
	java -classpath "./TerminalBin/:./*" Main crawlDoc

archiveMasterList:
	java -classpath "./TerminalBin/:./*" Main archiveMasterList
